exception error{
	string name;
};

interface HelloWorld{
	oneway void sayGoodbye(in string name,inout string number);
};

interface HelloService :HelloWorld{
	struct test{
		short id;
		string name;
	};
	typedef string id;
	const short number = 5;
	string sayHello(in string name,inout string number) raises (error);
	void shutdown(out string data);	
};